version: "3.9"

services:
  postgres:
    image: elestio/postgres:17
    # Si usas Mac M1/M2 puedes dejar esto activo:
    platform: linux/arm64
    container_name: kathencargos_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: KathEncargos      # BD creada al levantar el contenedor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres    # SOLO para desarrollo
      TZ: America/Managua

    ports:
      - "5433:5432"                  # host:contendor

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d KathEncargos"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: kathencargos_pgadmin
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PGADMIN_DEFAULT_EMAIL: kathEncargos@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      # Modo “desktop”, sin multiusuario ni master password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # Cargar siempre las definiciones de servers.json al arrancar
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"

    ports:
      - "5050:80"                    # pgAdmin en http://localhost:5050



    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  pgdata:
  pgadmin-data:
